name: tepetl
description: "Aplicación multiplataforma para el aprendizaje de lengua Náhuatl."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  csv: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

flutter:
  uses-material-design: true
  fonts:
   - family: SpaceGrotesk
     fonts:
      - asset: assets/fonts/SpaceGrotesk-Bold.ttf
      - asset: assets/fonts/SpaceGrotesk-Light.ttf
      - asset: assets/fonts/SpaceGrotesk-Medium.ttf
      - asset: assets/fonts/SpaceGrotesk-Regular.ttf
      - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
  assets:
   - assets/logo.png
   - assets/branding.png
   - assets/logo50.png
   - assets/logo_b.png
   - assets/logob50.png
   - assets/logo800.png
   - assets/logoa12.png
   - assets/logo300.png

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  color_dark: "#111111"
  image: assets/logo.png
  branding: assets/branding.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#111111"
    image: assets/logoa12.png
    branding: null