// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVsNOzPLdt7nAA5BdWMJ3nuGUIL-WdKdw',
    appId: '1:690753911366:web:d82e45f5ae4302faa12847',
    messagingSenderId: '690753911366',
    projectId: 'tepetl-a9d78',
    authDomain: 'tepetl-a9d78.firebaseapp.com',
    storageBucket: 'tepetl-a9d78.firebasestorage.app',
    measurementId: 'G-05B8WHW0K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRyVhKeUMQHWpjq1TTDr89ITqRJGGyT10',
    appId: '1:690753911366:android:108efca11cbc2b2ca12847',
    messagingSenderId: '690753911366',
    projectId: 'tepetl-a9d78',
    storageBucket: 'tepetl-a9d78.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVsNOzPLdt7nAA5BdWMJ3nuGUIL-WdKdw',
    appId: '1:690753911366:web:1d41918aa3e6c258a12847',
    messagingSenderId: '690753911366',
    projectId: 'tepetl-a9d78',
    authDomain: 'tepetl-a9d78.firebaseapp.com',
    storageBucket: 'tepetl-a9d78.firebasestorage.app',
    measurementId: 'G-QQP56F8QGF',
  );
}
